title: test site
#logo
description: environmental science | BA
theme: jekyll-theme-minimal

library(ggplot2)
library(dplyr)
library(sf)
library(rnaturalearth)
library(classInt)
library(gridExtra)
library(eHOF)

iv <- readRDS ("~/Downloads/IV_data (1).RDS")

hof_plot <- function(species){
  trees_data <- iv %>%
    filter(COMMON_NAME == species)
  lat_seq <- seq(from = floor(min(trees_data$LAT)), to = ceiling(max(trees_data$LAT)), by = 0.5)
  trees_bands <- data.frame(
    Lat_band = lat_seq,
    avg_IV = numeric(length(lat_seq))
  )
  for (i in 1:length(lat_seq)){
    lat_min <- lat_seq[i] - 0.5
    lat_max <- lat_seq[i] + 0.5
    band_data <- trees_data %>%
      filter(LAT >= lat_min & LAT <= lat_max)
    trees_bands$avg_IV[i] <- mean(band_data$IV, na.rm = TRUE)
  }
  trees_bands <- trees_bands[complete.cases(trees_bands$avg_IV),]
  hof_model <- HOF(
    trees_bands$avg_IV,
    trees_bands$Lat_band,
    modeltypes = c("I","II","III","IV","V"),
    family = gaussian,
    bootstrap = 100,
    test = 'AIC'
  )
  best_model <- pick.model(hof_model, modeltypes = c("I","II","III","IV","V"), test = 'AIC')
  predicted_response <- predict(hof_model, model = best_model,
                                newdata = seq(min(trees_bands$Lat_band), max(trees_bands$Lat_band), by = 0.1))
  scaled_response <- predicted_response * max(trees_bands$avg_IV)
  ggplot(trees_bands, aes(x = Lat_band, y = avg_IV)) +
    geom_point(color = "grey60") +
    geom_line(data = data.frame(lat_band = seq(min(trees_bands$Lat_band),
                                               max(trees_bands$Lat_band), by = 0.1),
                                predicted_IV = scaled_response),
              aes(x = lat_band, y = predicted_IV), color = "black") +
    geom_vline(xintercept = Para(hof_model, model = best_model)$opt, color = "red", linetype = "dashed") +
    labs(title = paste("Latitudinal IV pattern", species), x = "Latitude", y = "IV (Importance Value")
}
hof_plot("black oak")
unique(iv$COMMON_NAME)
hof_plot("red pine")


fia <- readRDS("~/Downloads/FIA_tree_master1 (2).RDS")
fia
head(fia_spcd)
first(unique(fia$GRIDID))
mean(fia_spcd$DIA, na.rm = TRUE)
fia_grid <- fia[fia$GRIDID == unique(fia$GRIDID)[1],]
mean(fia_grid$DIA, na.rm = TRUE)
results <- list()
results
tree <- fia_spcd[fia$COMMON_NAME == "black oak"] %>%
  head(10)
target <- fia %>%
  group_by(GRIDID, LAT, LON, COMMON_NAME, DIA, HT, FGROWCFAL, FMORTCFAL, FREMVCFAL) %>%
  filter(COMMON_NAME %in% c("red pine","black oak"))

baby <- target %>%
  filter(DIA <= 3.5)
red_pine_baby <- baby %>%
  filter(COMMON_NAME == "red pine")
black_oak_baby <- baby %>%
  filter(COMMON_NAME == "black oak")

adult <- target %>%
  filter(DIA >= 3.6)
red_pine_adult <- adult %>%
  filter(COMMON_NAME == "red pine")
black_oak_adult <- adult %>%
  filter(COMMON_NAME == "black oak")

ggplot()+
  geom_point(data = red_pine_baby, aes(x = LON, y = LAT), size = 1,color = "red") +
  geom_point(data = red_pine_adult, aes(x = LON, y = LAT), size = 1, color = "grey10")
  
ggplot()+
  geom_point(data = black_oak_baby, aes(x = LON, y = LAT), size = 1, color = "red") +
  geom_point(data = black_oak_adult, aes(x = LON, y = LAT), size = 1, color = "grey10")

